{
 "title": "Firehose Timeboard",
 "description": "Firehose monitoring dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "influxdb" },
   { "name": "prometheus_datasource", "label": "Prometheus Data Source", "query": "prometheus" },
   { "name": "organisation", "label": "Organisation", "query": "gojek,godata,goid,pilotdata" },
   { "name": "landscape", "label": "Landscape", "query": "id,th,vn,gl" },
   {
    "name": "firehose",
    "label": "Firehose Name",
    "query": "SHOW TAG VALUES FROM \"firehose_jvm_\" WITH KEY=\"app\""
   },
   {
    "name": "pods",
    "label": "Pods",
    "query": "SHOW TAG VALUES FROM \"firehose_jvm_\" WITH KEY=\"host\" WHERE \"app\" =~ /^$firehose$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Health",
   "type": "flant-statusmap-panel",
   "description": "This shows the health of the firehose. In case the firehose is not running fine you would see a red bar",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Uptime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "firehose_uptime",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
     ]
    }
   ]
  },
  {
   "title": "Type Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sink",
     "type": "stat",
     "description": "The type of sink of the firehose. It could be 'log', 'HTTP', 'DB', 'redis', 'influx' or 'Elasticsearch'",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "first" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "firehose.kafka.process_partitions_time",
       "query": "SELECT last(\"sink\") as filter from (SELECT \"sink\", \"value\" from \"firehose_sink_messages_total\"  where $timeFilter AND \"app\"=~/^$firehose.*$/ )",
       "select": [
        [
         { "params": [ "/^$consumer_group$/" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Team",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 2, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "first" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(\"team\") as filter from (SELECT \"team\", \"value\" from \"firehose_sink_messages_total\"  where $timeFilter AND app=~/^$firehose.*$/ )",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Proto Schema",
     "type": "stat",
     "description": "The proto class used for creating the firehose.",
     "gridPos": { "h": 3, "w": 12, "x": 6, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "first" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(\"proto\") as filter from (SELECT \"proto\", \"value\" from \"firehose_sink_messages_total\"  where $timeFilter AND app=~/^$firehose.*$/ )",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Stream",
     "type": "stat",
     "description": "The stream where the input topic is read from",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "first" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(\"stream\") as filter from (SELECT \"stream\", \"value\" from \"firehose_sink_messages_total\"  where $timeFilter AND app=~/^$firehose.*$/ )",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Replica",
     "type": "stat",
     "description": "The number of pods required by a firehose to reach the desired state",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "kube_deployment_spec_replicas{deployment=~\"$firehose\"}"
      }
     ]
    },
    {
     "title": "Running Pods",
     "type": "stat",
     "description": "Number of pods currently running successfully for the firehose",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_running{container=~\"$firehose\"})",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "kube_pod_container_status_running",
       "query": "SELECT sum(\"gauge\") FROM \"kube_pod_container_status_running\" WHERE \"container\" =~ /^$firehose$/ AND $timeFilter GROUP BY time(1s) fill(linear)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "container", "operator": "=~", "value": "/^$firehose$/" }
       ]
      }
     ]
    },
    {
     "title": "Deployment Age",
     "type": "stat",
     "description": "Time since the firehose was last created/edited",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "time() - kube_deployment_created{deployment=~\"$firehose\"}"
      }
     ]
    },
    {
     "title": "Pod Restart Count",
     "type": "table-old",
     "description": "Number of times the pods of this firehose restarted",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_restarts_total{container=\"$firehose\"}) by (pod)"
      }
     ]
    },
    {
     "title": "ConsumerLag: MaxLag",
     "type": "graph",
     "description": "The maximum lag in terms of number of records for any partition in this window. An increasing value over time is your best indication that the consumer group is not keeping up with the producers.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_kafka_consumer_",
       "select": [
        [
         { "params": [ "fetch_manager_records-lag-max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Message Received",
     "type": "graph",
     "description": "Sum of all messages received from Kafka per pod",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "client-id" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_kafka_consumer_",
       "query": "SELECT last(\"kafka.consumer.consumer-fetch-manager-metrics-records-consumed-total\") FROM \"v2_jolokia\" WHERE (\"app\" =~ /^$firehose$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         {
          "params": [
           "fetch_manager_records-consumed-total"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Message Sent Successfully",
     "type": "graph",
     "description": "Messages sent successfully to the sink per batch per pod",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_sink_messages_total",
       "query": "SELECT sum(\"value\") FROM \"firehose.messages.count\" WHERE (\"app\" =~ /^$firehose$/ AND \"success\" = 'true') AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose$/" },
        { "condition": "AND", "key": "success", "operator": "=", "value": "true" }
       ]
      }
     ]
    },
    {
     "title": "Message Sent Failed",
     "type": "graph",
     "description": "Messages failed to be pushed into the sink per batch per pod. \nIn case of HTTP sink, if status code is not in retry codes configured, the records will be dropped.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_sink_messages_total",
       "query": "SELECT sum(\"value\") FROM \"firehose.messages.count\" WHERE (\"app\" =~ /^$firehose$/ AND \"success\" = 'false') AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" },
        { "condition": "AND", "key": "success", "operator": "=", "value": "false" }
       ]
      }
     ]
    },
    {
     "title": "Message Dropped",
     "type": "graph",
     "description": "In case of HTTP sink, when status code is not in retry codes configured, the records are dropped. This metric captures the dropped messages count.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_cause",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "cause" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_sink_messages_drop_total",
       "query": "SELECT sum(\"value\") FROM \"firehose.messages.dropped.count\" WHERE (\"app\" =~ /^$firehose$/ AND \"success\" = 'false') AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Batch size Distribution",
     "type": "graph",
     "description": "99p of batch size distribution for pulled and pushed messages per pod",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Pulled: $tag_host",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_source_kafka_pull_batch_size_total",
       "query": "SELECT max(\"99_percentile\") AS \"99P\" FROM \"firehose_source_kafka_pull_batch_size_total\" WHERE (\"app\" =~ /^$firehose.*$/) AND $timeFilter GROUP BY time(1m), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "99_percentile" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "99P" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      },
      {
       "alias": "Pushed: $tag_host",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_sink_push_batch_size_total",
       "query": "SELECT max(\"99_percentile\") AS \"99p\" FROM \"firehose_sink_push_batch_size_total\" WHERE (\"host\" =~ /^$firehose.*$/) AND $timeFilter GROUP BY time(1m), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "99_percentile" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "99p" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Time spent in firehose",
     "type": "graph",
     "description": "Latency introduced by firehose (time before sending to sink - time when reading from Kafka).\nNote: It could be high if the response time of the sink is higher as subsequent batches could be delayed",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 35 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_host($col)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_pipeline_execution_lifetime_milliseconds",
       "query": "SELECT max(\"99_percentile\") AS \"99p\", max(\"95_percentile\") AS \"95p\", max(\"50_percentile\") AS \"50p\" FROM \"firehose.latency\" WHERE (\"app\" =~ /^$firehose$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "99_percentile" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "99p" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Time spent in pipeline",
     "type": "graph",
     "description": "Time difference between Kafka ingestion and sending to sink (Time before sending to sink - Time of Kafka ingestion)",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_host($col)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_pipeline_end_latency_milliseconds",
       "query": "SELECT max(\"99_percentile\") AS \"99p\", max(\"95_percentile\") AS \"95p\", max(\"50_percentile\") AS \"50p\" FROM \"firehose.lifetime.till.execution\" WHERE (\"app\" =~ /^$firehose$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "99_percentile" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "99p" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Sink Response Time",
     "type": "graph",
     "description": "Different percentile of the response time of the sink",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 35 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_host($col)",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_sink_response_time_milliseconds",
       "query": "SELECT max(\"99_percentile\") AS \"99P\", max(\"95_percentile\") AS \"95P\", max(\"50_percentile\") AS \"50P\" FROM \"firehose.sink.response.time\" WHERE (\"app\" =~ /^$firehose$/) AND $timeFilter GROUP BY time(1m), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "99_percentile" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "99P" ], "type": "alias" }
        ],
        [
         { "params": [ "95_percentile" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "95P" ], "type": "alias" }
        ],
        [
         { "params": [ "50_percentile" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "50P" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Pods Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Lifetime",
     "type": "table-old",
     "description": "JVM Uptime of each pod",
     "gridPos": { "h": 12, "w": 10, "x": 0, "y": 38 },
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "firehose_jvm_",
       "query": "SELECT last(\"uptime_Uptime\") FROM \"v2_jolokia\" WHERE (\"app\" =~ /^$firehose$/) AND time > now() - 1m GROUP BY time($__interval), \"host\"",
       "select": [
        [
         { "params": [ "Uptime" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Cpu Load",
     "type": "graph",
     "description": "Returns the \"recent cpu usage\" for the Java Virtual Machine process. This value is a double in the [0.0,1.0] interval. A value of 0.0 means that none of the CPUs were running threads from the JVM process during the recent period of time observed, while a value of 1.0 means that all CPUs were actively running threads from the JVM 100% of the time during the recent period being observed. Threads from the JVM include the application threads as well as the JVM internal threads. All values betweens 0.0 and 1.0 are possible depending of the activities going on in the JVM process and the whole system. If the Java Virtual Machine recent CPU usage is not available, the method returns a negative value.",
     "gridPos": { "h": 6, "w": 14, "x": 10, "y": 38 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "alias": "Pod: $tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_operating_system_",
       "select": [
        [
         { "params": [ "ProcessCpuLoad" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Cpu Time",
     "type": "graph",
     "description": "Returns the CPU time used by the process on which the Java virtual machine is running. The returned value is of nanoseconds precision but not necessarily nanoseconds accuracy",
     "gridPos": { "h": 6, "w": 14, "x": 10, "y": 44 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "Pod: $tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_operating_system_",
       "select": [
        [
         { "params": [ "ProcessCpuTime" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka Consumer Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Assigned partitions",
     "type": "graph",
     "description": "Consumer Group Metrics: The number of partitions currently assigned to this consumer (per pod)",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "[[tag_host]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "client-id" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_kafka_consumer_",
       "query": "SELECT last(\"coordinator_assigned-partitions\") FROM \"firehose_kafka_consumer_\" WHERE (\"host\" =~ /^$pods$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         {
          "params": [
           "coordinator_assigned-partitions"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Consumer Number of Request/second",
     "type": "graph",
     "description": "Global Request Metrics: The average number of requests sent per second per pod",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 39 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "client-id" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_kafka_consumer_",
       "query": "SELECT mean(\"kafka.consumer.consumer-metrics-request-rate\") FROM \"v2_jolokia\" WHERE (\"app\" =~ /^$firehose$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "metrics_request-rate" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Records Consumed Rate/second",
     "type": "graph",
     "description": "Topic-level Fetch Metrics: The average number of records consumed per second for a specific topic per pod.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "client-id" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_kafka_consumer_",
       "query": "SELECT mean(\"kafka.consumer.consumer-fetch-manager-metrics-records-consumed-rate\") FROM \"v2_jolokia\" WHERE (\"app\" =~ /^$firehose$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         {
          "params": [
           "fetch_manager_records-consumed-rate"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Bytes Consumed Rate/second",
     "type": "graph",
     "description": "Topic-level Fetch Metrics: The average number of bytes consumed per second per pod",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 39 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Pod: $tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "client-id" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_kafka_consumer_",
       "query": "SELECT mean(\"kafka.consumer.consumer-fetch-manager-metrics-bytes-consumed-rate\") FROM \"v2_jolokia\" WHERE (\"app\" =~ /^$firehose$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         {
          "params": [
           "fetch_manager_bytes-consumed-rate"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Fetch Rate/second",
     "type": "graph",
     "description": "Fetch Metrics: The number of fetch requests per second per pod",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "client-id" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_kafka_consumer_",
       "query": "SELECT mean(\"kafka.consumer.consumer-fetch-manager-metrics-fetch-rate\") FROM \"v2_jolokia\" WHERE (\"app\" =~ /^$firehose$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "fetch_manager_fetch-rate" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Max Fetch Latency",
     "type": "graph",
     "description": "Fetch Metrics: The max time taken for a fetch request per pod",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 46 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "client-id" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_kafka_consumer_",
       "query": "SELECT max(\"kafka.consumer.consumer-fetch-manager-metrics-fetch-latency-max\") FROM \"v2_jolokia\" WHERE (\"app\" =~ /^$firehose$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         {
          "params": [
           "fetch_manager_fetch-latency-max"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Average Fetch Latency",
     "type": "graph",
     "description": "Fetch Metrics: The average time taken for a fetch request per pod",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "client-id" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_kafka_consumer_",
       "query": "SELECT mean(\"kafka.consumer.consumer-fetch-manager-metrics-fetch-latency-avg\") FROM \"v2_jolokia\" WHERE (\"app\" =~ /^$firehose$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         {
          "params": [
           "fetch_manager_fetch-latency-avg"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Average Fetch Size",
     "type": "graph",
     "description": "Fetch Metrics: The average number of bytes fetched per request per pod",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 46 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "client-id" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "firehose_kafka_consumer_",
       "query": "SELECT mean(\"kafka.consumer.consumer-fetch-manager-metrics-fetch-size-avg\") FROM \"v2_jolokia\" WHERE (\"app\" =~ /^$firehose$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(linear)",
       "select": [
        [
         { "params": [ "fetch_manager_fetch-size-avg" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Max Fetch Size",
     "type": "graph",
     "description": "Fetch Metrics: The max number of bytes fetched per request per pod",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "client-id" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_kafka_consumer_",
       "query": "SELECT max(\"kafka.consumer.consumer-fetch-manager-metrics-fetch-size-max\") FROM \"v2_jolokia\" WHERE (\"app\" =~ /^$firehose$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "fetch_manager_fetch-size-max" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Commit Rate/second",
     "type": "graph",
     "description": "Consumer Group Metrics: The number of commit calls per second per pod",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "client-id" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_kafka_consumer_",
       "query": "SELECT mean(\"kafka.consumer.consumer-coordinator-metrics-commit-rate\") FROM \"v2_jolokia\" WHERE (\"app\" =~ /^$firehose$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "coordinator_commit-rate" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Consumer Active Connections Count",
     "type": "graph",
     "description": "Global Connection Metrics: The current number of active connections per pod",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "client-id" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_kafka_consumer_",
       "query": "SELECT mean(\"kafka.consumer.consumer-metrics-connection-count\") FROM \"v2_jolokia\" WHERE (\"app\" =~ /^$firehose$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "metrics_connection-count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "New Connections Creation Rate/second",
     "type": "graph",
     "description": "Global Connection Metrics: New connections established per second in the window per pod",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 53 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "client-id" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_kafka_consumer_",
       "query": "SELECT mean(\"kafka.consumer.consumer-metrics-connection-creation-rate\") FROM \"v2_jolokia\" WHERE (\"app\" =~ /^$firehose$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         {
          "params": [
           "metrics_connection-creation-rate"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Connections Close Rate/second",
     "type": "graph",
     "description": "Global Connection Metrics: Connections closed per second in the window per pod",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "client-id" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_kafka_consumer_",
       "query": "SELECT mean(\"kafka.consumer.consumer-metrics-connection-close-rate\") FROM \"v2_jolokia\" WHERE (\"app\" =~ /^$firehose$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "metrics_connection-close-rate" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Consumer Outgoing Byte Rate/S",
     "type": "graph",
     "description": "Global Request Metrics: The average number of outgoing bytes sent per second to all servers per pod",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 60 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "client-id" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "firehose_kafka_consumer_",
       "query": "SELECT mean(\"kafka.consumer.consumer-metrics-outgoing-byte-rate\") FROM \"v2_jolokia\" WHERE (\"app\" =~ /^$firehose$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(linear)",
       "select": [
        [
         { "params": [ "metrics_outgoing-byte-rate" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Avg time between poll",
     "type": "graph",
     "description": "Average time spent between poll per pod",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "client-id" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_kafka_consumer_",
       "query": "SELECT mean(\"kafka.consumer.consumer-metrics-time-between-poll-avg\") FROM \"v2_jolokia\" WHERE (\"app\" =~ /^$firehose$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "metrics_time-between-poll-avg" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Max time between poll",
     "type": "graph",
     "description": "Max time spent between poll per pod",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 60 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "client-id" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_kafka_consumer_",
       "query": "SELECT mean(\"kafka.consumer.consumer-metrics-time-between-poll-max\") FROM \"v2_jolokia\" WHERE (\"app\" =~ /^$firehose$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "metrics_time-between-poll-max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Sync rate",
     "type": "graph",
     "description": "Consumer Group Metrics: The number of group syncs per second per pod. Group synchronization is the second and last phase of the rebalance protocol. Similar to join-rate, a large value indicates group instability",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "client-id" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_kafka_consumer_",
       "query": "SELECT mean(\"kafka.consumer.consumer-coordinator-metrics-sync-rate\") FROM \"v2_jolokia\" WHERE (\"app\" =~ /^$firehose$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "coordinator_sync-rate" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Consumer Network IO rate /second",
     "type": "graph",
     "description": "The average number of network operations (reads or writes) on all connections per second per pod",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 67 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "client-id" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_kafka_consumer_",
       "query": "SELECT mean(\"kafka.consumer.consumer-metrics-network-io-rate\") FROM \"v2_jolokia\" WHERE (\"app\" =~ /^$firehose$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "metrics_network-io-rate" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Rebalance Rate /hour",
     "type": "graph",
     "description": "Rate of rebalance the consumer. More details here : https://cwiki.apache.org/confluence/display/KAFKA/KIP-429%3A+Kafka+Consumer+Incremental+Rebalance+Protocol",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 67 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "client-id" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_kafka_consumer_",
       "query": "SELECT mean(\"kafka.consumer.consumer-coordinator-metrics-failed-rebalance-rate-per-hour\") FROM \"v2_jolokia\" WHERE (\"app\" =~ /^$firehose$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         {
          "params": [
           "coordinator_rebalance-rate-per-hour"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Average Commit latency",
     "type": "graph",
     "description": "Consumer Group Metrics: The average time taken for a commit request per pod",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 67 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "client-id" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_kafka_consumer_",
       "query": "SELECT mean(\"kafka.consumer.consumer-coordinator-metrics-commit-latency-avg\") FROM \"v2_jolokia\" WHERE (\"app\" =~ /^$firehose$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "coordinator_commit-latency-avg" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Max Commit latency",
     "type": "graph",
     "description": "Consumer Group Metrics: The max time taken for a commit request per pod",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "client-id" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_kafka_consumer_",
       "query": "SELECT last(\"kafka.consumer.consumer-coordinator-metrics-commit-latency-max\") FROM \"v2_jolokia\" WHERE (\"app\" =~ /^$firehose$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "coordinator_commit-latency-max" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Avg Rebalance latency",
     "type": "graph",
     "description": "Average Rebalance Latency for the consumer per pod",
     "gridPos": { "h": 7, "w": 8, "x": 9, "y": 74 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "client-id" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_kafka_consumer_",
       "query": "SELECT sum(\"kafka.consumer.consumer-coordinator-metrics-rebalance-latency-avg\") FROM \"v2_jolokia\" WHERE (\"app\" =~ /^$firehose$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(linear)",
       "select": [
        [
         {
          "params": [
           "coordinator_rebalance-latency-avg"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Max Rebalance latency",
     "type": "graph",
     "description": "Max Rebalance Latency for the consumer per pod",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 74 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "client-id" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_kafka_consumer_",
       "query": "SELECT last(\"kafka.consumer.consumer-coordinator-metrics-rebalance-latency-max\") FROM \"v2_jolokia\" WHERE (\"app\" =~ /^$firehose$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         {
          "params": [
           "coordinator_rebalance-latency-max"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Error",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "FATAL ERROR",
     "type": "table",
     "description": "Count of all the exception raised by the pods which can restart the firehose",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "firehose.error.event",
       "query": "select  class as errors, sum as count from (select sum(\"value\") from \"firehose_error_event\"  WHERE $timeFilter AND  \"app\" =~ /^$firehose$/ AND \"type\"='fatal'  group by \"class\")",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "NON FATAL ERROR",
     "type": "table-old",
     "description": "Count of all the exception raised by the firehose which will not restart the firehose and firehose will keep retrying",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "class" ], "type": "tag" }
       ],
       "measurement": "firehose.error.event",
       "query": "select  class as errors, sum as count from (select sum(\"value\") from \"firehose_error_event\"  WHERE $timeFilter AND  \"app\" =~ /^$firehose$/ AND \"type\"='nonfatal'  group by \"class\")",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "NON_FATAL_ERROR" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Memory Usage",
     "type": "graph",
     "description": "Details of heap memory usage:\n1. Max: The amount of memory that can be used for memory management\n2. Used: The amount of memory currently in use",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host:($col)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_jvm_",
       "query": "SELECT mean(\"heap_memory_usage_HeapMemoryUsage.max\") AS \"max\", mean(\"heap_memory_usage_HeapMemoryUsage.used\") AS \"used\", mean(\"heap_memory_usage_HeapMemoryUsage.committed\") AS \"committed\" FROM \"v2_jolokia\" WHERE (\"host\" =~ /^$pods$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "HeapMemoryUsage.max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "max" ], "type": "alias" }
        ],
        [
         { "params": [ "HeapMemoryUsage.used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "used" ], "type": "alias" }
        ],
        [
         { "params": [ "HeapMemoryUsage.committed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "committed" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Non-Heap Memory Usage",
     "type": "graph",
     "description": "Details of non-heap memory usage:\n1. Max: The amount of memory that can be used for memory management\n2. Used: The amount of memory currently in use",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host($col)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_jvm_",
       "select": [
        [
         { "params": [ "NonHeapMemoryUsage.max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "max" ], "type": "alias" }
        ],
        [
         { "params": [ "NonHeapMemoryUsage.used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "used" ], "type": "alias" }
        ],
        [
         { "params": [ "NonHeapMemoryUsage.committed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "committed" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "GC: Memory Pool Collection Usage",
     "type": "graph",
     "description": "For a garbage-collected memory pool, the amount of used memory includes the memory occupied by all objects in the pool including both reachable and unreachable objects. This is for all the names in the type: MemoryPool",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 91 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host($col)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_jvm_",
       "select": [
        [
         {
          "params": [
           "class_count_java_memory_pool_CollectionUsage.max"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "max" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "class_count_java_memory_pool_CollectionUsage.used"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "used" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "class_count_java_memory_pool_CollectionUsage.committed"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "committed" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "GC: Memory Pool Peak Usage",
     "type": "graph",
     "description": "For a garbage-collected memory pool, the amount of used memory includes the memory occupied by all objects in the pool including both reachable and unreachable objects. This is for all the names in the type: MemoryPool",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 91 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host($col)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_jvm_",
       "select": [
        [
         {
          "params": [
           "class_count_java_memory_pool_PeakUsage.max"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "max" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "class_count_java_memory_pool_PeakUsage.used"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "used" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "class_count_java_memory_pool_PeakUsage.committed"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "committed" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "GC: Memory Pool Usage",
     "type": "graph",
     "description": "For a garbage-collected memory pool, the amount of used memory includes the memory occupied by all objects in the pool including both reachable and unreachable objects. This is for all the names in the type: MemoryPool",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 91 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: Max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_jvm_",
       "select": [
        [
         {
          "params": [
           "class_count_java_memory_pool_Usage.max"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "max" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "class_count_java_memory_pool_Usage.used"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "used" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "class_count_java_memory_pool_Usage.committed"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "committed" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Collection Count",
     "type": "graph",
     "description": "The total number of collections that have occurred per pod. Rather than showing the absolute value we are showing the difference to see the rate of change more easily.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_jvm_",
       "query": "SELECT difference(sum(\"garbage_collection_CollectionCount\")) FROM \"v2_jolokia\" WHERE (\"host\" =~ /^$pods$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         {
          "params": [
           "garbage_collection_CollectionCount"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "GC Collection Time",
     "type": "graph",
     "description": "The approximate accumulated collection elapsed time in milliseconds per pod. Rather than showing the absolute value we are showing the difference to see the rate of change more easily.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_jvm_",
       "query": "SELECT difference(\"garbage_collection_CollectionTime\") FROM \"v2_jolokia\" WHERE $timeFilter and host =~ \"$pods\" GROUP BY \"name\"",
       "select": [
        [
         {
          "params": [
           "garbage_collection_CollectionTime"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Thread Count",
     "type": "graph",
     "description": "daemonThreadCount: Returns the current number of live daemon threads per pod\npeakThreadCount: Returns the peak live thread count since the Java virtual machine started or peak was reset per pod\nthreadCount: Returns the current number of live threads including both daemon and non-daemon threads per pod",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 92 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host : $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_jvm_",
       "select": [
        [
         { "params": [ "thread_count_DaemonThreadCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "daemonThreadCount" ], "type": "alias" }
        ],
        [
         { "params": [ "thread_count_PeakThreadCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "peakThreadCount" ], "type": "alias" }
        ],
        [
         { "params": [ "thread_count_ThreadCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "threadCount" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Class Count",
     "type": "graph",
     "description": "loadedClass: Displays number of classes that are currently loaded in the Java virtual machine per pod\nunloadedClass: Displays the total number of classes unloaded since the Java virtual machine has started execution",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 92 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_jvm_",
       "select": [
        [
         { "params": [ "class_count_LoadedClassCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "loadedClass" ], "type": "alias" }
        ],
        [
         { "params": [ "class_count_UnloadedClassCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "unloadedClass" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Code Cache Memory after GC",
     "type": "graph",
     "description": "The code cache memory usage in the memory pools at the end of a GC per pod",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 92 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host- $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_jvm_",
       "query": "SELECT \"garbage_collection_LastGcInfo.memoryUsageAfterGc.G1 Old Gen.committed\", \"garbage_collection_LastGcInfo.memoryUsageAfterGc.PS Old Gen.committed\", \"garbage_collection_LastGcInfo.memoryUsageAfterGc.CMS Old Gen.committed\" FROM \"v2_jolokia\" WHERE ((\"name\" = 'G1 Old Generation' OR \"name\" = 'PS MarkSweep' OR \"name\" = 'ConcurrentMarkSweep')) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         {
          "params": [
           "garbage_collection_LastGcInfo.memoryUsageAfterGc.Code Cache.committed"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "committed" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "garbage_collection_LastGcInfo.memoryUsageAfterGc.Code Cache.used"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "used" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "garbage_collection_LastGcInfo.memoryUsageAfterGc.Code Cache.max"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "max" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Compressed Class Space after GC",
     "type": "graph",
     "description": "The compressed class space memory usage in the memory pools at the end of a GC per pod",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 100 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host- $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_jvm_",
       "query": "SELECT \"garbage_collection_LastGcInfo.memoryUsageAfterGc.G1 Old Gen.committed\", \"garbage_collection_LastGcInfo.memoryUsageAfterGc.PS Old Gen.committed\", \"garbage_collection_LastGcInfo.memoryUsageAfterGc.CMS Old Gen.committed\" FROM \"v2_jolokia\" WHERE ((\"name\" = 'G1 Old Generation' OR \"name\" = 'PS MarkSweep' OR \"name\" = 'ConcurrentMarkSweep')) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         {
          "params": [
           "garbage_collection_LastGcInfo.memoryUsageAfterGc.Compressed Class Space.committed"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "committed" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "garbage_collection_LastGcInfo.memoryUsageAfterGc.Compressed Class Space.used"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "used" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "garbage_collection_LastGcInfo.memoryUsageAfterGc.Compressed Class Space.max"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "max" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Metaspace after GC",
     "type": "graph",
     "description": "The metaspace memory usage in the memory pools at the end of a GC per pod",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 100 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host- $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_jvm_",
       "query": "SELECT mean(\"garbage_collection_LastGcInfo.memoryUsageAfterGc.Metaspace.committed\") AS \"committed\", mean(\"garbage_collection_LastGcInfo.memoryUsageAfterGc.Metaspace.used\") AS \"used\", mean(\"garbage_collection_LastGcInfo.memoryUsageAfterGc.Metaspace.max\") AS \"max\" FROM \"v2_jolokia\" WHERE (\"host\" =~ /^$pods$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         {
          "params": [
           "garbage_collection_LastGcInfo.memoryUsageAfterGc.Metaspace.committed"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "committed" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "garbage_collection_LastGcInfo.memoryUsageAfterGc.Metaspace.used"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "used" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "garbage_collection_LastGcInfo.memoryUsageAfterGc.Metaspace.max"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "max" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Par Eden Space after GC",
     "type": "graph",
     "description": "The eden space memory usage in the memory pools at the end of a GC per pod",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 100 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host- $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_jvm_",
       "query": "SELECT mean(\"garbage_collection_LastGcInfo.memoryUsageAfterGc.Par Eden Space.committed\") AS \"committed\", mean(\"garbage_collection_LastGcInfo.memoryUsageAfterGc.Par Eden Space.used\") AS \"used\", mean(\"garbage_collection_LastGcInfo.memoryUsageAfterGc.Par Eden Space.max\") AS \"max\" FROM \"v2_jolokia\" WHERE (\"host\" =~ /^$pods$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         {
          "params": [
           "garbage_collection_LastGcInfo.memoryUsageAfterGc.Par Eden Space.committed"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "committed" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "garbage_collection_LastGcInfo.memoryUsageAfterGc.Metaspace.used"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "used" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "garbage_collection_LastGcInfo.memoryUsageAfterGc.Metaspace.max"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "max" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Par Survivor Space after GC",
     "type": "graph",
     "description": "The survivor space memory usage in the memory pools at the end of a GC per pod",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 108 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host- $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_jvm_",
       "query": "SELECT mean(\"garbage_collection_LastGcInfo.memoryUsageAfterGc.Par Survivor Space.committed\") AS \"committed\", mean(\"garbage_collection_LastGcInfo.memoryUsageAfterGc.Par Survivor Space.used\") AS \"used\", mean(\"garbage_collection_LastGcInfo.memoryUsageAfterGc.Par Survivor Space.max\") AS \"max\" FROM \"v2_jolokia\" WHERE (\"host\" =~ /^$pods$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         {
          "params": [
           "garbage_collection_LastGcInfo.memoryUsageAfterGc.Par Survivor Space.committed"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "committed" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "garbage_collection_LastGcInfo.memoryUsageAfterGc.Metaspace.used"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "used" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "garbage_collection_LastGcInfo.memoryUsageAfterGc.Metaspace.max"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "max" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Tenured Space after GC",
     "type": "graph",
     "description": "The tenured space memory usage in the memory pools at the end of a GC per pod",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 108 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host- $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_jvm_",
       "query": "SELECT mean(\"garbage_collection_LastGcInfo.memoryUsageAfterGc.Tenured Gen.committed\") AS \"committed\", mean(\"garbage_collection_LastGcInfo.memoryUsageAfterGc.Tenured Gen.used\") AS \"used\", mean(\"garbage_collection_LastGcInfo.memoryUsageAfterGc.Tenured Gen.max\") AS \"max\" FROM \"v2_jolokia\" WHERE (\"host\" =~ /^$pods$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         {
          "params": [
           "garbage_collection_LastGcInfo.memoryUsageAfterGc.Tenured Gen.committed"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "committed" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "garbage_collection_LastGcInfo.memoryUsageAfterGc.Metaspace.used"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "used" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "garbage_collection_LastGcInfo.memoryUsageAfterGc.Metaspace.max"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "max" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "File Descriptor",
     "type": "graph",
     "description": "Number of file descriptor per pod\n1. Open: Current open file descriptors\n2. Max: Based on config max allowed",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 108 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_operating_system_",
       "select": [
        [
         { "params": [ "OpenFileDescriptorCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "open" ], "type": "alias" }
        ],
        [
         { "params": [ "MaxFileDescriptorCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "max" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Retry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Retry Requests",
     "type": "graph",
     "description": "Request retries per min per pod",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_retry_total",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Back Off time",
     "type": "graph",
     "description": "Time spent per pod backing off",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_retry_backoff_sleep_milliseconds",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "HTTP Sink", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Response Count Total",
   "type": "table",
   "description": "Total number of response received by firehose from the HTTP service across different status code",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "alias": "$tag_status_code",
     "groupBy": [
      { "params": [ "status_code" ], "type": "tag" }
     ],
     "measurement": "firehose_sink_http_response_code_total",
     "query": "SELECT sum(value) as total FROM \"firehose_sink_http_response_code_total\" WHERE (\"app\" =~ /^$firehose.*$/) and $timeFilter GROUP BY \"status_code\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$firehose.*$/" }
     ]
    }
   ]
  },
  {
   "title": "Success Response Count",
   "type": "graph",
   "description": "Total number of 2xx and 3xx response received by firehose from the HTTP service",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_status_code",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "status_code" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "firehose_sink_http_response_code_total",
     "query": "SELECT sum(\"value\") FROM \"firehose_sink_http_response_code_total\" WHERE (\"app\" =~ /^$firehose.*$/ AND \"status_code\" =~ /^[23].*/) AND $timeFilter GROUP BY time($__interval), \"status_code\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" },
      { "condition": "AND", "key": "status_code", "operator": "=~", "value": "/^[23].*/" }
     ]
    }
   ]
  },
  {
   "title": "Unsuccessful Response Count",
   "type": "graph",
   "description": "Total number of 4xx and 5xx response received by firehose from the HTTP service",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_status_code",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "status_code" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "firehose_sink_http_response_code_total",
     "query": "SELECT sum(\"value\") FROM \"firehose_sink_http_response_code_total\" WHERE (\"app\" =~ /^$firehose.*$/ AND \"status_code\" =~ /^[45].*/) AND $timeFilter GROUP BY time($__interval), \"status_code\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" },
      { "condition": "AND", "key": "status_code", "operator": "=~", "value": "/^[45].*/" }
     ]
    }
   ]
  },
  {
   "title": "No Response Count",
   "type": "graph",
   "description": "Total number of No response received by firehose from the HTTP service",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "No response (status_code: $tag_status_code)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "status_code" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "firehose_sink_http_response_code_total",
     "query": "SELECT mean(\"value\") FROM \"firehose_http_response_code\" WHERE (\"app\" =~ /^$firehose$/ AND \"status_code\" = '') AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "status_code", "operator": "!~", "value": "/^[2345].*/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$firehose$/" }
     ]
    }
   ]
  },
  { "title": "MongoDB Sink", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Inserted Documents Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "SELECT sum(\"value\") FROM \"firehose_sink_mongo_inserted_total\" WHERE (\"app\" =~ /^$firehose.*$/) AND $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "Updated Documents Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "query": "SELECT sum(\"value\") FROM \"firehose_sink_mongo_updated_total\" WHERE (\"app\" =~ /^$firehose.*$/) AND $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "Total Modified Documents Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "query": "SELECT sum(\"value\") FROM \"firehose_sink_mongo_modified_total\" WHERE (\"app\" =~ /^$firehose.*$/) AND $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "Filter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filter Type",
     "type": "stat",
     "description": "Type of filter in the firehose. It will be one of the \"none\", \"key\", \"message\"",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "first" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "firehose_pipeline_end_latency_milliseconds",
       "query": "SELECT last(\"filter\") as filter from (SELECT \"filter\", \"value\" from \"firehose_sink_messages_total\"  where $timeFilter AND host=~/^$firehose.*$/ )",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Messages filtered",
     "type": "graph",
     "description": "Sum of all the messages filtered because of the filter condition per pod.",
     "gridPos": { "h": 7, "w": 20, "x": 4, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "firehose_source_kafka_messages_filter_total",
       "query": "SELECT mean(\"value\") FROM \"firehose_kafka_messages_received\" WHERE (\"app\" =~ /^$firehose$/) AND $timeFilter GROUP BY time(1m) fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$firehose.*$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}